-- 코드를 입력하세요

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES as S
JOIN BOOK as B ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR as A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(S.SALES_DATE) = '2022' AND MONTH(S.SALES_DATE) = '01'
GROUP BY 1, 3
ORDER BY 1, 3 DESC;


