/*
    1. 자동차 종류가 '세단' 혹은 'SUV'인 자동차 -> 
    2. 2022년 11월 1일 ~ 2022년 11월 30일까지 대여 가능?
    3. 30일간 대여 금액이 50이상 200 미만인 자동차에 대해서
*/


SELECT H.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*(100-P.DISCOUNT_RATE)/100*30) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as H
JOIN CAR_RENTAL_COMPANY_CAR as C on H.CAR_ID = C.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as P on C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV') AND 
P.DURATION_TYPE = '30일 이상' AND
H.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE < '2022.12.01' AND END_DATE > '2022.11.01'
)
GROUP BY H.CAR_ID, C.CAR_TYPE
HAVING FEE>= 500000 and FEE < 2000000
ORDER BY 3 DESC, 2, 1 DESC;
