
SELECT U.USER_ID, 
        U.NICKNAME, 
        CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) as 전체주소,
        CONCAT(LEFT(U.TLNO, 3), '-', SUBSTR(U.TLNO, 4, 4), '-', RIGHT(U.TLNO, 4)) as 전화번호
FROM USED_GOODS_BOARD as B
JOIN USED_GOODS_USER as U on B.WRITER_ID = U.USER_ID
WHERE U.USER_ID IN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING COUNT(BOARD_ID) >= 3
)
GROUP BY U.USER_ID
ORDER BY 1 DESC;
/*
SELECT *
FROM USED_GOODS_USER */