SELECT YEAR(O.SALES_DATE) as YEAR, MONTH(O.SALES_DATE) as MONTH, U.GENDER as GENDER, COUNT(distinct U.USER_ID) as USERS
FROM ONLINE_SALE as O
JOIN USER_INFO as U on O.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1,2,3;